apps_rails/blog/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts
  resources :home, :only => [:index]
  resources :authors 

  get "author/:id/posts" => "authors#posts", :as => "post_author"

  namespace :admin do
    resources :authors
  end
end

apps_rails/blog/app/models/author.rb
class Author < ActiveRecord::Base
	has_many :posts
	validates_presence_of :name, :bio
end

apps_rails/blog/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  delegate :post, to: :post
end

apps_rails/blog/app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :author
	delegate :name, to: :author, :prefix => "author"
	delegate :bio, to: :author, :prefix => "author"
end

apps_rails/blog/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

apps_rails/blog/app/controllers/admin/authors_controller.rb
class Admin::AuthorsController < AdminController

	def index
		@authors = Author.all		
	end
end

apps_rails/blog/app/controllers/admin/home_controller.rb
class Admin::HomeController < AdminController
end

apps_rails/blog/app/controllers/admin/posts_controller.rb
class Admin::PostsController < AdminController
end

apps_rails/blog/app/controllers/admin_controller.rb
class AdminController < ApplicationController
	before_filter :authenticate_user!
end

apps_rails/blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

apps_rails/blog/app/controllers/authors_controller.rb
class AuthorsController < ApplicationController

	before_action :set_author, only: [:show, :edit, :destroy, :update, :posts]
	
	#GET /authors
	def index
		@authors = Author.all
	end

	#GET /authors/new
	def new
		@author = Author.new
	end

	def edit
	end

	def show
	end

	def posts
		@posts = @author.posts
		render "posts/index"
	end


	#POST /authors
	def create
		@author = Author.new(author_params)
		if @author.save
			redirect_to authors_path, :notice => "Author #{author_params[:name]} registered sucessfully!"
		else
			flash[:notice] = "Athor can not registered. Fill in the empty fiels!"
			render :new
		end	
	end

	def update
		if @author.update_attributes(author_params)
			redirect_to authors_path, :notice => "Author #{@author.name} update successfully"		
		else
			render :edit
		end
	end

	def destroy
		@author.destroy
		redirect_to authors_path, :notice => "Author delete successfully"
	end


	private

	def author_params
		params.require(:author).permit(:name, :bio)
	end

	def set_author
		@author = Author.find(params[:id])
	end
end

apps_rails/blog/app/controllers/home_controller.rb
class HomeController < ApplicationController
	
	def index
	end

end

apps_rails/blog/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

apps_rails/blog/app/helpers/application_helper.rb
module ApplicationHelper
end

apps_rails/blog/app/helpers/home_helper.rb
module HomeHelper
end

apps_rails/blog/app/helpers/posts_helper.rb
module PostsHelper
end

apps_rails/blog/app/views/admin/authors/index.html.erb
<h1>List of Authorshf</h1>

apps_rails/blog/app/views/authors/_form.html.erb
<%= form_for @author do |f| %>

<%= f.label :name %><br>
<%= f.text_field :name%>
<br>

<%= f.label :bio %><br>
<%= f.text_area :bio %>
<br>

<%= f.submit "Save New Author" %>

<%end%>

<%= link_to("Back Authors", authors_path) %>

apps_rails/blog/app/views/authors/edit.html.erb
<h1> Edit Author <%= @author.name %></h1>

<%= render "form" %>

apps_rails/blog/app/views/authors/index.html.erb
<h1>Lista de Autores</h1>

<p><%= flash[:notice] %></p>

<%= @authors.size %> Autores Cadastrados <br>

<table>
	<tr>
		<th>ID</th>
		<th>Nome</th>
		<th>Biografia</th>	
		<th>Registrado em</th>
		<th>Option</th>
	</tr>

	<% @authors.each do |author| %>

		<tr>
			<td><%= author.id %></td>
			<td> <%= author.name %> </td>
			<td> <%= author.bio %> </td>
			<td> <%= author.created_at %> </td>
			<td><%= link_to "Edit", edit_author_path(author) %></td>
			<td><%= link_to "Show", author_path(author) %></td>
			<td><%= link_to "Delete", author_path(author), method: :delete, data: {confirm: "Want to actually delete this?"} %></td>
			<td><%= link_to "List Posts", post_author_path(author) %></td>

		</tr>	

	<% end %>
	
</table>

<%= link_to("New Author", new_author_path) %>

apps_rails/blog/app/views/authors/new.html.erb
<h1>Register New Author</h1>

<p><%= flash[:notice] %><p/>

<%= render "form" %>

apps_rails/blog/app/views/authors/show.html.erb
<h1>Show Author</h1>

<p>Name: <%= @author.name %></p>
<p>Biografia: <%= @author.bio %></p>

<%= link_to :Back, authors_path %>
<%= link_to :Edit, edit_author_path(@author) %>

apps_rails/blog/app/views/home/index.html.erb
<h1> Pagina Inicial </h1>

apps_rails/blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

<% if signed_in? %>
<p><%= current_user.email %></p>
<p><%= link_to "Logout", destroy_user_session_path, method: :delete %></p>
<%end%>
</head>
<body>

<%= yield %>

</body>
</html>

apps_rails/blog/app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_field :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

apps_rails/blog/app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

apps_rails/blog/app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.body %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

apps_rails/blog/app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

apps_rails/blog/app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>